# Generated by Django 3.2 on 2021-04-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210420_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
